### ISSUE TITLE
Implement Google Sign Up/Sign In 

### ISSUE THREAD

**Issue by 007jithinjose** [Morphclue/apollusia#191] opened 2024-10-11 18:05 UTC
This task focuses on integrating Google Sign-In  The goal is to allow users to sign up and sign in using their Google accounts, store their data in database, and redirect them to the appropriate pages upon successful authentication.
Please assign me this issue and add hacktober fest  accepted label.
This feature will make logging in easier for users.

**Comment by Morphclue** [comment] 2024-10-12 07:13
We are currently using [Keycloak](https://www.keycloak.org/) as an identity provider, which supports major social login providers like Google, Facebook, etc. Therefore this seems to be a duplicate of #159.

**Comment by 007jithinjose** [comment] 2024-10-12 07:18
but i cant seem to find the options for social logins anywhere though not in the  login or signup? Am i missing it ?

**Comment by Morphclue** [comment] 2024-10-12 07:23
They are currently not enabled, because I didn't have time to get into it, but that's the task for #159. The login mask from keycloak will have additional buttons that have social providers. We also have a theme in place, but it's a bit more complicated to bundle it up correctly on the server with our current deployment workflow. Just to give you a preview how it will look like: 
![image](https://github.com/user-attachments/assets/52f0d6a4-7a01-4bc7-b4a9-5ec6924afdcf)

**Comment by 007jithinjose** [comment] 2024-10-12 07:28
ok

**Comment by Morphclue** [comment] 2024-10-12 07:29
Closed as duplicate of #159.

**Closed by Morphclue** 2024-10-12 07:29 UTC
Labels: enhancement
